### ISSUE TITLE
Call tech-specific memory compiler

### ISSUE THREAD

**Issue by stevobailey** [ucb-bar/hammer#110]
After running MacroCompiler, it's possible we want to run a technology-specific memory compiler if the memories are not pre-compiled. We should add functionality to do this.

**Comment by donggyukim** [comment]
We also want to use CACTI-based compilers for architectural research.

**Comment by colinschmidt** [comment]
Working on the IR now

**Comment by colinschmidt** [comment]
Fixed by #341
