### ISSUE TITLE
Floorplan width should be optional for hardmacros

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/hammer#113]
Its not used in the code path anyways

**Comment by edwardcwang** [comment]
Might be useful to keep the info around to do IR checking

**Comment by jwright6323** [comment]
> Might be useful to keep the info around to do IR checking

I'm not sure I understand what this comment is saying. What info and why?

**Comment by edwardcwang** [comment]
The width/height for hardmacros. There can be a piece of code that checks that two hardmacros aren't placed on top of each other, etc just based on the info in the Hammer IR.

**Comment by jwright6323** [comment]
I don't understand what you're proposing- it is currently a requirement and @colinschmidt is suggesting to make it optional. Are you saying we should continue to make it mandatory? Not disagreeing, I just don't understand what you're trying to communicate.

**Comment by edwardcwang** [comment]
I am mainly just wondering if we should keep floorplan width/height as mandatory in order to facilitate this kind of check. (Though if the width/height is not specified, then that macro could just be excluded from the check list I suppose.)

**Comment by jwright6323** [comment]
I think this is a good discussion to have soon, as it might set a precedent for future issues. I see pros and cons to both approaches

Mandatory:
- Pro: Checks are easy, "forces" designers to include this info
- Con: May lead some people to set it to 0 at first and then create an unreliable source of info. Also more front-loaded work.
Optional
- Pro: Flexible, agile
- Con: Extra work / code overhead in writing checks that need to support optional fields

**Comment by edwardcwang** [comment]
"Checks are easy, "forces" designers to include this info" -> also enforces more of a "correct-by-construction" style of design.

"Extra work / code overhead in writing checks that need to support optional fields" -> also reduces the strength/validity of the checks

**Comment by colinschmidt** [comment]
Ya'll need to write some large floorplans. I stand by my desire for this field being optional.

**Comment by edwardcwang** [comment]
Yeah I can see why this would be useful when writing large floorplans by hand. I was thinking more in a world where most of the floorplanning constraints are generated, this would be less of a usability issue.

**Comment by colinschmidt** [comment]
I eagerly await such a world.

**Comment by jwright6323** [comment]
For the record I agree with @colinschmidt, but I do think it's not a cut-and-dried situation.
