### ISSUE TITLE
Add vlsi.inputs.hierarchical.custom_config array

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#127]
Useful for hierarchical to specify custom configs for each layer in the hierarchy

@colinschmidt

**Comment by colinschmidt** [comment]
Ok I'm looking at this now but don't have a good solution for it yet.

**Comment by colinschmidt** [comment]
Current plan after off-line discussions is something like:
```
vlsi.inputs.hierarchical.constraints:
   -BootRom:
      -vlsi.inputs.clocks: [ {name: "clock", period: 2ns} ]
```
which could also support:
```
vlsi.inputs.hierarchical.constraints:
  BootRom: "bootrom.json"
  BootRom_meta: "transcludejson"
```
This enables hammer to resolve these hierarchical constraints as overriding the default global constraints so that `get_setting(...)` just works ™️
