### ISSUE TITLE
Ability to merge custom IP into tech json

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/hammer#161]
IP should be able to generate its own tech json that can be merged/appended into the regular tech json.

**Comment by edwardcwang** [comment]
I think this is a duplicate of https://github.com/ucb-bar/hammer/issues/141?

**Comment by colinschmidt** [comment]
Yes sorry was writing things down from stream of consciousness so I didn't forget anything.

Sorry for the noise.
