### ISSUE TITLE
bashism in sourcem.sh

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/hammer#162]
In csh it does not print the nice helpful message like it does in bash

**Comment by edwardcwang** [comment]
IIRC bash and csh aren't compatible in syntax... we'll probably need to create a `sourceme.csh` or something using a translation that looks something like http://joelinoff.com/blog/?page_id=235 (or even better, automatically generate it for DRY, reduction of maintenance burden)

**Comment by colinschmidt** [comment]
I think because the shebang has just `/bin/sh` its a little confusing. I'm also not sure if `source`ing even looks at that.

We could obviously generate this but I was wondering if there was a small enough subset or someway to use the shebang to solve this.

**Comment by edwardcwang** [comment]
I think the standard is that `/bin/sh` is a Bourne-compatible shell and that if we want csh we need to explicitly reference `/bin/csh` or equivalent.

Unfortunately I don't think there is a subset of common syntax where you could write a script that works in both, at least not without ugly hacks :-(

**Comment by harrisonliew** [comment]
No more sourceme :)
