### ISSUE TITLE
"path" in hammer_tech is confusing

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#167]
The variable we call "path" in hammer_tech might be better referred to as "prefix". Consider the following example - "mytech28" is a path but we really use it like a prefix to reference paths.

This will also allow us to rename the confusing "installs" and "tarballs" into something a intuitive structure e.g. TarballPrefix, PathPrefix, VariablePrefix.

In install:
```
   {
      "path": "mytech28",
      "base var": "technology.mytech28.install_dir"
    }
```

In libraries
```
    {
      "lef file": "mytech28/LEF_files/stdcells.lef",
      ...
    }
```

**Comment by jwright6323** [comment]
Adding on to this issue that it's also confusing that there's no special syntax for prefixes. I thought I had filed this issue before, but can't find it now.

Taking the example above:
```
    {
      "lef file": "mytech28/LEF_files/stdcells.lef",
      ...
    }
```

This leads one to believe that there is a file somewhere called `/path/to/mytech28/LEF_files/stdcells.lef`, and that I need to go find out where `/path/to` is. However, `mytech28` is a magic string that is expanded to some other `/path/to/this/thing` which may or may not contain the actual characters `m y t e c h 2 8`. Having it use a variable-like syntax (e.g. `${mytech28}/LEF_files/stdcells.lef` is much clearer, IMO.

This also applies to the `library_prefix` stuff (#270).

**Comment by harrisonliew** [comment]
"path" -> "id" and "base var" -> "path" in new Hammer.
