### ISSUE TITLE
Cell blacklist ("don't use") API

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#178]
Provide a way for technologies / project generators to blacklist the use of certain standard cells (known to cause DRC errors, etc).

Implementation detail: we can probably add it in `init_design` after running the main `init_design` or something.

**Comment by colinschmidt** [comment]
This is a good plan I have some of this reasonably separated out in the cad-plugins folder, hopefully I can submit a PR before Monday.
