### ISSUE TITLE
Units should handle negative values

### ISSUE THREAD

**Issue by seldridge** [ucb-bar/hammer#192]
I was trying to input some negative temperatures for standard cell corners. `ValueWithUnit` isn't expecting anything to start with an optional `-`. I think this should be supported? Something like: `^(-?[\d.]+)` ?

The regex is here: https://github.com/ucb-bar/hammer/blob/master/src/hammer-vlsi/hammer_vlsi/units.py#L66

**Comment by colinschmidt** [comment]
Nice catch.
