### ISSUE TITLE
How does HAMMER handle relative paths

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/hammer#211]
For example, if you want to have a git submodule for a BAG IP which contains its own HAMMER IR yaml file, how are relative paths resolved? Do we need to add a feature to allow this?

**Comment by edwardcwang** [comment]
Paths are resolved using something that looks like the following:

```
vlsi.technology.extra_libraries:
  - prefix:
      path: ...
      prefix: "serdes"
    library:
      "lef file": "serdes/my_serdes.lef"
```

https://github.com/ucb-bar/hammer/blob/df59c1ac1ffc60f2596b4149e8dc634ff9821fc3/src/hammer-vlsi/defaults.yml#L49

**Comment by jwright6323** [comment]
@pkerichang I think this will work.

Thanks!
