### ISSUE TITLE
Parse unittests.sh output more intelligently

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#215]
Right now if a test fails, the stdout contains everything and the kitchen sink. We can parse the output more intelligently and only display the tests that actually fail.

**Comment by colinschmidt** [comment]
Another way to make the github CI more usable would be to just have the bot delete its old comments whenever there is a new run.

**Comment by jwright6323** [comment]
Bumping this because walls of text on #326 are annoying me. Is it possible to just switch to Travis or something? Not sure what the differences between the hammer-robot and Travis are.

**Comment by edwardcwang** [comment]
I'll add this to my stack of things to work on

**Comment by harrisonliew** [comment]
Moved to pytest, much more intelligible output now.
