### ISSUE TITLE
Nicer internal-API/DRY implementation of relative paths

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/hammer#232]
I found a snippet in a plugin that makes paths relative, but it assumes the paths are relative to `cwd` not the directory from which yaml/json came from.
I think there is a nice API improvement here where we note the directory we load a yaml/json from and we have a `Path` type for strings that are really paths/files and when the dev calls `get_setting` it automagically returns the right path.

Related: #270

**Comment by jwright6323** [comment]
I assume this will affect change the existing relative path behavior? (not saying this should preclude us from making this change)

**Comment by colinschmidt** [comment]
We could also make the `Path` type have an option that changes what the path is relative to i.e. `cwd` or `file_dir`

**Comment by jwright6323** [comment]
I think that is useful. We should probably figure out which is more intuitive to set as a default (I think `file_dir`)

**Comment by colinschmidt** [comment]
I think this should be addressed with #276

**Comment by edwardcwang** [comment]
Related to #270

**Comment by edwardcwang** [comment]
Closing in favour of #270, #276
