### ISSUE TITLE
Figure out dependency tracking/integration with build tools

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/hammer#234]
We should have some way of generating Makefiles or includes to improve build management (we don't want to reinvent the wheel here)

**Comment by edwardcwang** [comment]
And includes support for bazel/scons/other build systems

**Comment by jwright6323** [comment]
Example use case we need to support:
We have a programmatically-generated hierarchy, so the makefile targets are not known before tool invocation, so we should be generating some (or all) of the Makefile, etc.

**Comment by edwardcwang** [comment]
Further discussion: call the generated Makefile/etc, but also enable users to go into a `generated/` dir and call `make` themselves (risky)

**Comment by jwright6323** [comment]
@harrisonliew are you interested in helping with this? Maybe we can converge on a single Makefile generation method.
