### ISSUE TITLE
--to_step vs --through_step

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/hammer#310]
It might be useful to have separate `--to_step` and `--through_step` CLI options. Currently the `--to_step` option behaves like what I would imagine `--through_step` would, by executing the step inclusively. IMO this is the more useful variant, so it's fine as-is, but if we also want a non-inclusive variant the names should change.

**Comment by edwardcwang** [comment]
Another option is `--until-step`

**Comment by jwright6323** [comment]
Also a good option. That matches scala's `until` and `to` behavior (although I find `to` ambiguous in that case as well)
