### ISSUE TITLE
SDC punch-through API

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#323]
API to pass through a SDC blackbox through `vlsi.inputs`.

**Comment by jwright6323** [comment]
What does "SDC blackbox" mean in this context?

**Comment by edwardcwang** [comment]
This is an API to pass hand-written snippets of SDC directly into the synthesis tool since Hammer doesn't abstract 100% of the APIs in SDC yet.

**Comment by colinschmidt** [comment]
Do you need something like this: https://github.com/ucb-bar/hammer/blob/obstructions-and-constraints/src/hammer-vlsi/hammer_vlsi.py#L2249 or more?

**Comment by edwardcwang** [comment]
Yep, except that I suppose one could use that API to pass through arbitrary stuff.

**Comment by edwardcwang** [comment]
Rename it and it's what is needed

**Comment by colinschmidt** [comment]
I'm doing this now
