### ISSUE TITLE
Altium PCB collateral

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/hammer#364]
This is somewhere in the nice-to-have/beginner-PR zone but it will be a bit of work. I think this is a good undergrad project.

With the new bumps API we should be able to generate library components for designs that are going directly on a PCB. Because we already use Altium, that's a good place to start. The footprint generation (or some components thereof) should live in a technology-specific plugin because it relates to the bump size and metallurgy, but the schematic generation can be fully tech-agnostic. The primary user input should be how to break apart the symbol pins into separate components (will show an EAGLE example of what the result should look like).

https://www.altium.com/documentation/18.0/display/ADES/((Creating+the+PCB+Footprint))_AD
https://techdocs.altium.com/display/SCRT/Script+Examples+Reference#DelphiScripts

**Comment by edwardcwang** [comment]
In the long run it might be good to try to do this in a PCB CAD tool independent way as well...

**Comment by jwright6323** [comment]
Agreed, I just didn't include that in the text of the issue but probably should have. I plan to do that in one combined effort. I think the "PCBTool" base class will end up being very simple at first.

**Comment by jwright6323** [comment]
This is closed by #420
