### ISSUE TITLE
Undocumented technology parameters

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#377]
Some CAD plugins depend on undocumented technology settings like `technology.core.std_cell_rail_layer`. We should document them in `defaults.yml`. For example, right now if we search "std_cell_rail_layer" in the repo we get no(!) results.

Marking as medium priority because it makes using these features harder.

**Comment by jwright6323** [comment]
oops, that was not intentional

**Comment by jwright6323** [comment]
Is this fixed by #382?

**Comment by edwardcwang** [comment]
lol, yes I accidentally fixed this without realizing it
