### ISSUE TITLE
Enforce top level IR inputs

### ISSUE THREAD

**Issue by dpgrubb13** [ucb-bar/hammer#380]
This came from a brief discussion with @jwright6323 and @harrisonliew  today.  I had a top level input `vlsi.inputs.bumps_mode: manual` that I typed wrong so the `bumps_mode`  was kept as `empty`, as in the defaults.  We think it may be a good idea to enforce some of the top level inputs like this to help catch some of these issues because it can cost real hours in syn/par time (and since you can always create your own custom data to use in the IR that wouldn't be enforced).

**Comment by edwardcwang** [comment]
Could this fit under the umbrella of #160?

**Comment by dpgrubb13** [comment]
Sure, I think that looks pretty much the same.
