### ISSUE TITLE
Floorplanning margins constraint is undocumented

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#381]
No results for margins show up if you search `margins` below:

https://github.com/ucb-bar/hammer/blob/a3723af74e8be17a57fe358b106f2f993830adf5/src/hammer-vlsi/defaults.yml

Note that Hammer does raise an error if you don't specify margins for toplevel.

https://github.com/ucb-bar/hammer/blob/a3723af74e8be17a57fe358b106f2f993830adf5/src/hammer-vlsi/hammer_vlsi/constraints.py#L211

`orientation` is also undocumented apparently...

**Comment by colinschmidt** [comment]
Perhaps we should also put the word floorplan in the placement constraints description as that is a commonly associated word (which currently returns only one non useful result when searched for)
