### ISSUE TITLE
Floorplan path should be optional for some types

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/hammer#416]
e.g. obstruction, dummy, toplevel

**Comment by edwardcwang** [comment]
Should this and #282 be merged?

Minor bikeshedding, I'd say let's keep the path of `toplevel` to be that it should be name of the top module for double proofing.

**Comment by jwright6323** [comment]
Ah I thought there was another issue, but I didn't type the right things in the search to find it. Yes, #282 is the same as this. IDK about keeping the path of `toplevel`, though. Seems like it does more harm than good by being confusing.

**Comment by colinschmidt** [comment]
In my opinion we shouldn't have two sources of information so don't keep around toplevel path.
