### ISSUE TITLE
Use python list/dict comprehensions instead of map/filter + lambdas

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/hammer#418]
@zhemao brought this up at the ADEPT retreat. Where possible we should probably go with list/dict comprehensions to be more readable and shorter. This is super low priority, but good to keep in mind when writing new code.

**Comment by edwardcwang** [comment]
No functional programming? NO WAY 😜😜

**Comment by edwardcwang** [comment]
On a more serious note, while I'm not opposed to code that uses list/dict comprehensions, I'm of the opinion that we could keep things flexible and hence no policy is necessarily required.

Personally I would say that the way I write Python has been influenced greatly by Scala...

**Comment by jwright6323** [comment]
Yeah, I mean almost all of mine has been `list(map(lambda ...))` also because scala, but I think we should leave this open. It's good to try use the features of the language if it makes the code clearer, which I believe it does.

**Comment by edwardcwang** [comment]
I suppose if you want to leave the issue open that's fine with me - I just feel that we should may not do a blanket replacement. If a contributor wants to use one or the other that is fine; I personally would like to continue using the functional programming paradigm (having been heavily influenced by Scala).

**Comment by jwright6323** [comment]
I don't think we should spend the time to change the existing code, so I guess this issue can be closed.

I know you like scala, and I have written a lot of scala-like python myself because it "makes sense", but (and this is an opinion, so you're welcome to disagree) I would find it difficult to argue that
```
y = list(map(lambda x: x + 1, filter(lambda x: x > 0, my_list)))
```
is more readable than
```
y = [x + 1 for x in my_list if x > 0]
```
and the latter is over 2x faster:
```
#!/usr/bin/env python

import time

def functional(x):
    return list(map(lambda x: x + 1, filter(lambda x: x > 0, my_list)))


def comprehension(x):
    return [x + 1 for x in my_list if x > 0]

my_list = list(range(1000000))


start = time.time()
functional(my_list)
stop = time.time()
print("functional: {}".format(stop - start))


start = time.time()
comprehension(my_list)                                                                                                                                                            
stop = time.time()
print("comprehension: {}".format(stop - start))
```

```
[07:21 PM] johnwright@yavin-2: ~ $ python3 test.py 
functional: 0.2836320400238037
comprehension: 0.11606597900390625
```

Food for thought.

**Comment by edwardcwang** [comment]
Hmm, thanks for the food for thought! I found some additional thoughts on the matter here (also food for thought): https://stackoverflow.com/questions/1247486/list-comprehension-vs-map

Filed #419 for an interesting digression I find somewhat interesting.
