### ISSUE TITLE
Steps need concept of state

### ISSUE THREAD

**Issue by harrisonliew** [ucb-bar/hammer#430]
In certain tools, there are certain settings that do not get written to their databases between steps. E.g. standard-cell cell obstructions that must be deleted for DRC early on are not carried over when you do a --from_step or --only_step <later step>.

We will need a way to figure out which sub-commands apply to what part in the design and insert them appropriately.

**Comment by colinschmidt** [comment]
https://github.com/ucb-bar/hammer-cad-plugins/issues/6

**Comment by jwright6323** [comment]
We basically probably want to be able to register hooks as "settings" hooks, and always run them first (i.e. before --from_step, --only_step, --to_step, and normal execution)

**Comment by jwright6323** [comment]
(from live discussions in the tapeout HQ) Now we're thinking you might want to have "anchors" so that any time you're passing that anchor, a --from_step or --only_step will trigger the settings. This is needed because some settings steps need to run after an init_design step.
