### ISSUE TITLE
HammerPlaceAndRouteTool.export_config_outputs should export top_module

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#453]
Compare https://github.com/ucb-bar/hammer/blob/9e1b24764edff4c710be21be8b0a813b55ac4e7c/src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py#L312 vs https://github.com/ucb-bar/hammer/blob/9e1b24764edff4c710be21be8b0a813b55ac4e7c/src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py#L231

Thanks to @jwright6323

**Comment by jwright6323** [comment]
I already fixed it, will include in #448

**Comment by jwright6323** [comment]
This is fixed by #448
