### ISSUE TITLE
plugin for OpenROAD

### ISSUE THREAD

**Issue by sequencer** [ucb-bar/hammer#489]
This EDA [project](https://github.com/The-OpenROAD-Project/) seems interesting, full opensource without NDA issue.
maybe this can be a solution for public flow generating for hammer.

**Comment by edwardcwang** [comment]
Related: #396

**Comment by kammoh** [comment]
Any updates or plans for upgrade to the priority?

**Comment by ilesser** [comment]
Would love to see open road integrated with hammer

**Comment by colinschmidt** [comment]
I think that this will remain a very low priority issue for the main hammer devs for a while.
The current focus of hammer and its devs is in helping users build chips easier and faster than before.
I don't believe OpenROAD has been used to tape-out any chips thus far and so would primarily be useful as an academic exercise. While I do see the value in this, it seems like a lot of infrastructure that doesn't align with the current dev's priorities.

All that being said I think most of us, would be happy to review PRs or discuss implementation issues if someone else wanted to lead the charge to get OpenROAD integrated into Hammer. We would encourage anyone interested to start a discussion here.

**Comment by sequencer** [comment]
I have tried OpenROAD for 1 time...
It has some pitfall for large designs, and only can be used with printf C++ to debug(that really sucks).
I think it needs to give a full documentation.
