### ISSUE TITLE
API to hot-fix vendor tech file bug 

### ISSUE THREAD

**Issue by sequencer** [ucb-bar/hammer#506]
https://github.com/ucb-bar/hammer/pull/500#issuecomment-528156766_
> I'm halfway through getting a script to change the rule decks & copy the GDS's, so this can be included in there as well.

we should implement this progress by the script too.
If we wanna change the foundry library, we should propose a simple post-install API to execute post-install script after extraction.

There are two types of change,
  1. ASCII encoded file which patch can be stored by patch file, this is quite straightforward and can be implemented by `https://github.com/techtonik/python-patch` or `/usr/bin/patch`.
  2. binary file which is generated by commercial EDA tools, this is a little complicated, since we should add additional hook to `hammer-tech`.

**Comment by harrisonliew** [comment]
`post_install_script` added by #511.
