### ISSUE TITLE
Does Hammer Support the Synopsys Toolchain?

### ISSUE THREAD

**Issue by farzadfch** [ucb-bar/hammer#524]
Not sure if this is the right place for asking these types of questions but does Hammer support the Synopsys toolchain; particularly DC?

**Comment by edwardcwang** [comment]
We have some support though we cannot release the source code for that plugin due to NDA-related concerns - can you e-mail us for further discussion?

**Comment by farzadfch** [comment]
Thanks for your response. Dropped you an email at (your first name)w@eecs.berkeley.edu
