### ISSUE TITLE
Replacement hook can't be targeted in flow control

### ISSUE THREAD

**Issue by harrisonliew** [ucb-bar/hammer#554]
Possibly a bug from #543?

Let's say we `make_replacement_hook("step_a", "step_b")`. `step_b` is correctly run instead of `step_a`. However, if doing a `--from_step` or similar, you have to target `step_a` instead of `step_b`. Logger info also prints out `step_a` when showing what it runs/skips.

Perhaps related: steps that are skipped (via removal hook) are still target in `do_post_steps` because it is seemingly still part of a transition.

**Comment by colinschmidt** [comment]
Related to all the other step issues and a overhaul to fix some of those should also fix this one.

**Comment by harrisonliew** [comment]
Also encountered: steps that are removed with a removal hook can still be targeted with pre-/post-insertion hooks. What happens is that Hammer lists the removed step as running, causing things like between-step actions to execute, but in reality the removed step itself is not actually run.

Behavior in this scenario needs to be defined.
