### ISSUE TITLE
gdspy 1.5 breaks asap7 patch 

### ISSUE THREAD

**Issue by sequencer** [ucb-bar/hammer#555]
Use up-to-date version `v1.5`.
```
    original_cells = asap7_original_gds.cell_dict
AttributeError: 'GdsLibrary' object has no attribute 'cell_dict'
```
I'll send a fix later.

**Comment by harrisonliew** [comment]
Seems like it changed from `cell_dict` to just `cells`.
Can you do some gdspy version checking in your patch?

**Comment by sequencer** [comment]
OK! I'll look into it later this week.
Tons of deadline comes to me:(

**Comment by colinschmidt** [comment]
Resolution: With ASAP 1p7 is released we will switch to a gdstk which is a new version of gdspy (which has been deprecated by the developer).
We will not be supporting gdspy going forward.
