### ISSUE TITLE
Github is unable to detect your license file

### ISSUE THREAD

**Issue by mithro** [ucb-bar/hammer#557]
Your LICENSE file is not detected by GitHub's license detection system. This means you won't be automatically included in various lists and scanned by various tools.

You can find out more about how the LICENSE detection at https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license

**Comment by edwardcwang** [comment]
Thanks for your interest in Hammer! The licence is a 3-clause BSD, so not sure why the server-side library (licensee) used by GitHub doesn't detect it. If you have any additional questions please feel free to be in touch.

**Comment by mithro** [comment]
@edwardcwang You probably want to figure out why the 3-clause BSD isn't being detected as lots of people use that information as authoritative.
