### ISSUE TITLE
ASAP7 version conflict in ASAP7 tutorial

### ISSUE THREAD

**Issue by njriasan** [ucb-bar/hammer#571]
Hi I'm trying to run through this example: https://chipyard.readthedocs.io/en/latest/VLSI/Tutorial.html. However when I download ASAP7 from the link given, it gives me release 1p6, but all the documentation and scripts seem to require 1p5. I'm not sure if this is the right place to this but these docs probably need to be updated with either a link to download 1p5 or scripts need to be updated to handle the changes in 1p6.

Additionally do you know if it is possible to download 1p5. I am a UC Berkeley masters student and I just need to run synthesis for a class project.

**Comment by dpgrubb13** [comment]
On the inst machines there is a pre-extracted 1p5 at `/home/ff/ee241/spring20-labs/`.

**Comment by edwardcwang** [comment]
Maybe we should make an archive of ASAP7 releases if upstream updates in incompatible ways. For example, where can we find a public archive of 1p5 right now?

**Comment by dpgrubb13** [comment]
I think we just have copies at BWRC and on the inst machines.

**Comment by brunosmmm** [comment]
Any plans to support 1p6? I am currently engaged in research using chipyard and was considering using hammer to push a design through, however I'm not affiliated with UCB so I can't get a hold of a 1p5 copy.

**Comment by colinschmidt** [comment]
We are waiting `1p7` release to update the plugins but you can contact the ASAP7 folks to get a copy of the `1p5` files.
