### ISSUE TITLE
Move all registers list for simulations into separate json

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/hammer#574]
Rather than inlining this field, since it is often very large, we should have it be a separate file and the current key become a path to that file.
This should speed up hammer's launch when these json fragments are included.

**Comment by jwright6323** [comment]
Does it even need to be a key? I thought you could just use multiple `-p` arguments to achieve the desired effect.

**Comment by colinschmidt** [comment]
Right now this is tracked as part of the output of the syn and par actions and an input to the sim action.
You could move it outside of this tracking system but I don't think that is a good idea since the simulation will not run correctly without it.
