### ISSUE TITLE
can't start or stop on steps in all tools except syn and par

### ISSUE THREAD

**Issue by ssteffl** [ucb-bar/hammer#585]
I would like to use HAMMER_EXTRA_ARGS="--to_step xxx" in a new drc tool. but cli_driver.py doesn't only adds these tooks to the syn/par tools on line ~1000.

**Comment by harrisonliew** [comment]
Ah, you see this now due to the fact that we changed some DRC/LVS plugins to write the runset files with steps. Previously, only syn/par used steps.

But, in general I agree that all tools should be able to start/stop on steps.

**Comment by colinschmidt** [comment]
Resolution: We should generalize `to/from_step` to be supported on all tools.

**Comment by harrisonliew** [comment]
Closed by #629
