### ISSUE TITLE
Error message during CTS using Innovus

### ISSUE THREAD

**Issue by harikumar27399** [ucb-bar/hammer#594]
I'm pretty new to using the Hammer VLSI flow. So I wanted to test the entire flow with the default tools (Genus, Innovus and Calibre) for a small example design 'spm' using the OSU 45nm FreePDK. During the Clock Tree Synthesis stage, I'm encountering the following error messages and due to these, the Innovus run gets aborted.

**ERROR: (IMPCCOPT-1135):	CTS found neither inverters nor buffers while balancing clock_tree clk. CTS cannot continue.
**ERROR: (IMPCCOPT-1054):	All clock trees have missing driver cells.
**ERROR: (IMPCCOPT-2196):	Cannot run ccopt_design because the command prerequisites were not met. Review the previous error messages for more details about the failure.

I have attached the design netlist and the complete Innovus log file for your reference. Do let me know if I have to provide any further information.

[innovus.txt](https://github.com/ucb-bar/hammer/files/5558516/innovus.txt)
[spm.txt](https://github.com/ucb-bar/hammer/files/5558550/spm.txt)

**Comment by harikumar27399** [comment]
Kindly have a look at the issue and let me know if I have to set some particular keys in the 45nm tech plugin/ configuration file to resolve the errors.

**Comment by harrisonliew** [comment]
Hi @harikumar27399! Thank you for trying out Hammer.

It seems like the .lib files don't define the clock inverters and buffers properly. You can manually select a set of cells from the library and specify them for CTS use using the following commands in the "cts Category Attributes". At the very minimum, you will need:

```
set_db cts_buffer_cells <list of buffer cells>
set_db cts_inverter_cells <list of inverter cells>
```

This can be done by adding these lines to the tech plugin via a hook. We can assist you then if these commands work.

**Comment by harikumar27399** [comment]
@harrisonliew Thanks a lot for the suggestion. I created a user-specified pre-insertion hook before the "clock_tree" step consisting the TCL statements you specified. The clock buffers and inverters are now being detected and CTS is able to proceed. However, I'm encountering the following error and multiple other warnings related to the 'clk' and 'rst' nets:

ERROR: (IMPCCOPT-5054):	Net clk is not completely connected after routing.
WARNING (NRIG-39) NanoRoute cannot route to pin PIN/clk of net clk because it might be a logical pin and does not have physical shapes. To fix the problem, check the pin connection in the netlist and ensure the pin shapes exist in the floorplan.

I have attached the entire log file for your reference, Kindly go through it and let me know what I'm missing.
[innovus2.txt](https://github.com/ucb-bar/hammer/files/5573975/innovus2.txt)

**Comment by harrisonliew** [comment]
I believe you are missing pin constraints, so you do not have the clk pin (or any other pin) placed. You need to specify constraints like this (Chipyard ASAP7 example): https://github.com/ucb-bar/chipyard/blob/f387c4b99424e869235f927aebcb7dabc643a6f5/vlsi/example.yml#L77

**Comment by harikumar27399** [comment]
@harrisonliew I'll work on specifying the pin constraints as you suggested and will get back to you if I face any issues.

Yes, I will submit a PR with the CTS and other settings as a technology hook once I'm done with setting up the entire flow without any errors.
