### ISSUE TITLE
Error while invoking Synopsys ICC par tool by Hammer

### ISSUE THREAD

**Issue by harikumar27399** [ucb-bar/hammer#596]
I'm encountering the following error while trying to run par using the Synopsys tool plugin available in the repository:

```
File "/chipyard_synopsys/vlsi/hammer/src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py", line 1921, in load_tool
    tool = tool_class()
TypeError: Can't instantiate abstract class ICC with abstract methods specify_power_straps, specify_std_cell_power_straps

```

It seems like the ICC tool class is inconsistent with the Hammer Tool base class. 
@harrisonliew @colinschmidt Kindly look into this and let me know what can be done to circumvent this issue.

**Comment by harrisonliew** [comment]
Indeed, the ICC plugin has never been validated and has not been updated at all to support the additional APIs (e.g. power straps) we have added over the years. Also, the plugin was for legacy ICC, not ICC II.

Do you have access to Cadence tools? Or, would you be willing to contribute to the ICC plugin?

Also, this issue fits better in github.com/ucb-bar/hammer-synopsys-plugins.

**Comment by harikumar27399** [comment]
@harrisonliew  I would be more than willing to contribute to the ICC plugin. Though, I would require proper guidance from your side as I'm not familiar with the Hammer source code as such.

**Comment by harrisonliew** [comment]
Sure! Email me at harrisonliew@berkeley.edu and we can set up an initial meeting to see where you're at with understanding Hammer.
