### ISSUE TITLE
Nangate45 Plugin

### ISSUE THREAD

**Issue by baichen318** [ucb-bar/hammer#597]
Hi all,

I have a quick question.

I was wondering where the hammer-nangate45-plugin is. I found a document describing the flow of Nangate45 (i.e., https://hammer-vlsi.readthedocs.io/en/latest/Examples/openroad-nangate45.html). and it needs the plugin.

Thank you very much!

Best regards,
Chen

**Comment by colinschmidt** [comment]
It is currently inlined into the hammer repo here: https://github.com/ucb-bar/hammer/tree/master/src/hammer-vlsi/technology/nangate45

We think that having tech plugins inlined in this way isn't ideal as it is atypical of other tech plugins. In the future, other open source tech plugins, as well as eventually the ones currently inlined, will be pulled out to match the structure of non-open source plugins and your expectation of a `hammer-nangate45-plugin` repo.

**Comment by baichen318** [comment]
> It is currently inlined into the hammer repo here: https://github.com/ucb-bar/hammer/tree/master/src/hammer-vlsi/technology/nangate45
> 
> We think that having tech plugins inlined in this way isn't ideal as it is atypical of other tech plugins. In the future, other open source tech plugins, as well as eventually the ones currently inlined, will be pulled out to match the structure of non-open source plugins and your expectation of a `hammer-nangate45-plugin` repo.

Thank you very much!
