### ISSUE TITLE
Support custom tcl chunks in SDC

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/hammer#60]
With this all other SDC issues can be lower priority as we can gradually shift from custom chunks to fully supported API

**Comment by edwardcwang** [comment]
Refinement: support custom TCL chunks by refactoring do_runs into a series of macro commands, each of which can be hooked and paused. Implement the necessary `HammerTool` infrastructure to do so.

**Comment by edwardcwang** [comment]
Fixed by #83
