### ISSUE TITLE
Cannot find hammer-cadence-plugin

### ISSUE THREAD

**Issue by shibizhao** [ucb-bar/hammer#636]
Hi,
I am a new user of chipyard. I visited `chipyard/vlsi/hammer-cadence-plugin`, but the page is 404.
I would like to know where I can get this plugin repo? 

Thx!

**Comment by harrisonliew** [comment]
Please email hammer-plugins-access@lists.berkeley.edu to request CAD tool plugins. Please see the relevant Chipyard documentation here: https://chipyard.readthedocs.io/en/stable/VLSI/Basic-Flow.html
