### ISSUE TITLE
Cadence pluggins long response time

### ISSUE THREAD

**Issue by jagjordi** [ucb-bar/hammer#637]
Hello,
I sent an email aproximately one month ago to [hammer-plugins-access@lists.berkeley.edu](mailto:hammer-plugins-access@lists.berkeley.edu) requesting the access to cadence and synopsys plugins but got no reply so far. I wanted to ask if it is normal that it takes this long or if maybe you missed my email.
Best regards

**Comment by edwardcwang** [comment]
@bwrcbcr  ?

**Comment by jagjordi** [comment]
Thank you! I got access now.
