### ISSUE TITLE
asap7 and Synthesis

### ISSUE THREAD

**Issue by Leon924** [ucb-bar/hammer#639]
I am wondering if it is possible to use Synopsys Design Compiler as Synthesis tool with asap7 PDK. Does DC support asap7 now? or I must use Cadence Genus?

**Comment by harrisonliew** [comment]
Unfortunately not. The team developing ASAP7 do not test it with Synopsys tools and our DC expects Milkyway LIBs, TLU+ cap tables, etc., which you can convert the existing libs to, but others who have tried have run into issues that are still unresolved: The-OpenROAD-Project/asap7#6

**Comment by pkusw** [comment]
Except Synopsys tools, I am wondering if  your team have  used other Synthesis tool to test ASAP7?

**Comment by harrisonliew** [comment]
The ASAP7 plugin works with Genus and Yosys.

**Comment by nachiket** [comment]
Was there a way to make this work with Synopsys tools? I did try to covert .lib to .db files but some FF cells don't make the cut and then Synopsys DC Compiler substitutes it's own FFGEN block and destroys timing (and also messes up area).
