### ISSUE TITLE
some problems when l  configure hammer

### ISSUE THREAD

**Issue by 1bing2** [ucb-bar/hammer#646]
when i set up hammer environment i encounter the problems as follow.but i have got the cadence plugins after i emailed ucb.

fatal: Needed a single revision
fatal: Unable to find current revision in submodule path 'vlsi/hammer-cadence-plugins'

**Comment by harrisonliew** [comment]
It looks like you're using Chipyard. Did you run the `init-vlsi.sh` script? https://chipyard.readthedocs.io/en/stable/VLSI/ASAP7-Tutorial.html?highlight=init-vlsi#initial-setup

**Comment by harrisonliew** [comment]
Superceded by issue in Chipyard.
