### ISSUE TITLE
Wierd pin width of two SRAMs

### ISSUE THREAD

**Issue by idwwwoqq808** [ucb-bar/hammer#687]
The dummy SRAMs: SRAM1RW256x64 and SRAM1RW256x128 have wierd pin widths. These two SRAMs have pin width of 0.384, while other SRAMs have pin width of 0.096. Will re-generating the SRAMs with sram_compiler.py shrink the pin width down to 0.096? If yes, how can I call the sram_compiler?

I'm trying to run PAR on MegaBoomConfig with Innovus and the icache has multiple SRAM1RW256x64. Innovus makes several DRC violations around pins of this SRAM. There is no DRC violations around other SRAMs.

**Comment by harrisonliew** [comment]
That is odd. No, the dummy SRAMs are generated using a different tool that is not included in Hammer. I'll look into this.

**Comment by idwwwoqq808** [comment]
Is there a way to prevent chipyard from using these two SRAMs?

**Comment by harrisonliew** [comment]
Yes, for now you can remove them from this file: https://github.com/ucb-bar/hammer/blob/master/src/hammer-vlsi/technology/asap7/sram-cache.json and then when you run MacroCompiler via Chipyard it won't map to those memories.

As an update: we've found the issue with the pin sizes, but we're having trouble matching the existing dimensions. Either we'll copy over the old dimensions or people using it will have to deal with the slight change. A PR will be forthcoming.

**Comment by harrisonliew** [comment]
Please try out #688!

**Comment by idwwwoqq808** [comment]
Got it. I've replaced those .gds and .lef files and run P&R of MegaBoomConfig with them.
Innovus may take a long time to finish.

**Comment by idwwwoqq808** [comment]
> Please try out #688!

The updated SRAMs worked fine. There were no DRC violations around them. Thanks for fixing it.
