### ISSUE TITLE
After abruptly terminating hammer-vlsi, the terminal needs reset

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/hammer#69]
The terminal is left in a weird state and I have to clear or reset it to normalize.

**Comment by edwardcwang** [comment]
Did you kill hammer-vlsi when it was printing out a colored line? Unfortunately if hammer gets killed before it can send out the end of the escape sequence, I'm not aware of techniques to programmatically reset the terminal.

**Comment by colinschmidt** [comment]
One example is there is an error in genus, it doesn't exit so I press control-c and then hammer also quits, and my terminal is messed up. I don't believe this happens if I control-c out of genus directly

**Comment by stevobailey** [comment]
Does your terminal not show any text on the screen, but typing a command seems to still work? Similar to how SSH password fields don't show what you're typing but will still receive your typed input. This is an issue with quitting CAD tools during execution that I've seen at times. It might be avoided by launching the tools in a new shell?
