### ISSUE TITLE
Broken public submodule

### ISSUE THREAD

**Issue by fitzfitsahero** [ucb-bar/hammer#694]
Some of your latest commits have broken chipyard when updating submodules. The hammer-mentor-plugins and hammer-synopsys-plugins are not public repos but are trying to be pulled in.

**Comment by harrisonliew** [comment]
The hammer-mentor-plugins and hammer-synopsys-plugins are not public repos to begin with. You need to request access, as documented in the Chipyard documentation: https://chipyard.readthedocs.io/en/stable/VLSI/Basic-Flow.html

The Chipyard setup has not yet been updated with any of the latest commits, so it shouldn't pull any of the recent changes in.
