### ISSUE TITLE
Don't touch / don't route options

### ISSUE THREAD

**Issue by boblinchuan** [ucb-bar/hammer#784]
https://github.com/ucb-bar/hammer/blob/0bbd2b5f6cc42c6a07563875d9fb882b26dde8de/hammer/par/innovus/__init__.py#L467

For preplaced pins in macros, this line currently lets Innovus still route the signal to the edge. This is not desired, e.g. if the macro pin is in the middle on a high layer and we want to leave it there.

The fix should be some combination of `set_dont_touch` and `set_db <nets> .skip_routing true`

**Comment by harrisonliew** [comment]
Note to self: after additional investigation, also doing this is incorrect: https://github.com/ucb-bar/hammer/blob/0bbd2b5f6cc42c6a07563875d9fb882b26dde8de/hammer/par/innovus/__init__.py#L403

Without `-insts`, it gets any pins on all BLOCK, PAD, and AREAIO macros that have pins matching that name wildcard. Similarly, if the top-level pin that the user defined as preplaced doesn't match exactly the pin name of the macro's pin, the promotion will not work.

Possible solution: query the hpins that are connected to the desired top-level pin, and input that to `set_promoted_macro_pin`. Then, investigate if we still need `set_dont_touch` and `.skip_routing true`.
