### ISSUE TITLE
Route obstruction options

### ISSUE THREAD

**Issue by boblinchuan** [ucb-bar/hammer#785]
https://github.com/ucb-bar/hammer-cadence-plugins/blob/902657b8bdba7aec12726d6d3c85a2639a4030ad/hammer/par/innovus/__init__.py#L1014

This line as is obstructs both routing and pg_nets. Is that the desired behavior? 

If we want to obstruct only routing but not pg_nets, we need the flag `except_pg_nets`

Use case: connecting a macro to power grid, but block routing over it to avoid unpredictable coupling effects.

**Comment by kenhoberkeley** [comment]
I agree. Let's PR this @harrisonliew ?

**Comment by boblinchuan** [comment]
As a note, this would require either (a) changing the default behavior or (b) adding another option to obstructions (e.g. route_only?)
