### ISSUE TITLE
Innovus routing layers not respected

### ISSUE THREAD

**Issue by ethanwu10** [ucb-bar/hammer#793]
### Background work

- [X] Yes, I searched the [documentation](https://hammer-vlsi.readthedocs.io/)
- [X] Yes, I searched in the [Support (Q&A)](https://github.com/ucb-bar/hammer/discussions/categories/support-q-a) section of the Discussions and read the [posting guidelines](https://github.com/ucb-bar/hammer/discussions/717)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/hammer/issues?q=)
- [X] This issue is specific to Hammer, i.e., does not belong in a plugin repository instead
- [X] My report does not contain sensitive info (e.g., PDK information under NDA)
- [ ] (If applicable) Yes, I searched the [Chipyard documentation](https://chipyard.readthedocs.io/)
- [ ] (If applicable) Yes, I searched the [Chipyard mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [ ] (If applicable) Yes, I searched the [Chipyard issues](https://github.com/ucb-bar/chipyard/issues?q=)

### Hammer version and plugin hashes

Release: (master)
Hash: 28a4824f68a3007d0d86ed0d997771ea0e41c973

### Other Setup

Innovus 211

### Current Behavior

Hammer Innovus tool sets keys for top/bottom routing layers *before* reading LEFs (including the tech LEF), which means the layers are not yet defined at the time of execution.
https://github.com/ucb-bar/hammer/blob/28a4824f68a3007d0d86ed0d997771ea0e41c973/hammer/par/innovus/__init__.py#L252-L273
This causes the `set_db` commands to error, resulting in the top and bottom layer settings getting ignored.

As a result, Sky130 has problems with routing since Innovus tries to route on a layer that it shouldn't (the bottom-most layer in the Sky130 tech-LEF is not a routing metal layer).

### Expected Behavior

Routing layers should be set after the tech LEF is loaded (do we want to bother splitting LEF load into two phases, or just handle routing layers after all LEFs are loaded?)

**Comment by harrisonliew** [comment]
Thanks for catching this bug. Can you just move this section (lines 252-262) down to the bottom of this `init_design` step?
