### ISSUE TITLE
Can't insert hooks before default first_step

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/hammer#87]
Not a huge deal because the first steps are short and don't affect QoR but still would be nice.

**Comment by edwardcwang** [comment]
@colinschmidt I added a test at #89 to insert before step1 and it appears that it should work.

**Comment by colinschmidt** [comment]
To clarify the issue the problem I was seeing was it was trying to resume from some pre_step that didn't exist yet. So I was able to get to the tool running but it failed when trying to resume.
